name: "Provision Terraform Infrastructure on AWS"

on: workflow_dispatch

jobs:
    terraform-apply:
        runs-on: ubuntu-latest
        environment: tf-env
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Terraform Setup
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.10.5"
                terraform_wrapper: false
            
            - name: Terraform Init
              run: terraform init -input=false

            - name: Terraform Validate
              run: terraform validate -no-color

            - name: Terraform Apply
              run: terraform apply -auto-approve -input=false
