name: "Destroy Terraform Infrastructure on AWS"

on: workflow_dispatch

jobs:
    terraform-destroy:
        runs-on: ubuntu-latest
        environment: prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_TOKEN_APP_TERRAFORM_IO: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
          TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
          TF_CLOUD_PROJECT: ${{ vars.TF_CLOUD_PROJECT }}
          TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Terraform Setup
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.10.5"
                terraform_wrapper: false
            
            - name: Terraform Init
              run: terraform init -input=false

            - name: Terraform Destroy
              run: terraform destroy -auto-approve -input=false
